// All text for CreateListing, MyListings and Transactions lives here.
// NOTE: Amharic (am) and Afaan Oromoo (om) texts must be reviewed by a native speaker.

export const DEFAULT_LANGUAGE = "am";

export const PAGE_LABELS = {
  am: {
    createListing: {
      title: "ምርት ይዘርዝሩ",
      loginRequired: "ምርት ለመዘርዘር መጀመሪያ ይግቡ።",
      successTitle: "ምርትዎ ተዘርዝሯል",
      successText: "ምርትዎ አሁን ለገዢዎች ይታያል።",
      createAnother: "ሌላ ምርት ይዘርዝሩ",
      viewMyListings: "የእኔን ምርቶች ይመልከቱ",
    },
    myListings: {
      title: "የእኔ ምርቶች",
      loading: "በመጫን ላይ…",
      empty: "እስካሁን ምንም ምርት አልዘረዘሩም።",
      errorText: "ምርቶችዎን መጫን አልተቻለም።",
      retry: "እንደገና ሞክር",
      tabAll: "ሁሉም",
      tabAvailable: "የሚገኙ",
      tabSold: "የተሸጡ",
      noneInFilter: "በዚህ ምድብ ምንም ምርት የለም።",
      addNew: "አዲስ ምርት ይዘርዝሩ",
    },
    transactions: {
      title: "ግብይቶቼ",
      loading: "በመጫን ላይ…",
      empty: "እስካሁን ምንም ግብይት የለም።",
      errorText: "ግብይቶችን መጫን አልተቻለም።",
      retry: "እንደገና ሞክር",
      youAreBuyer: "እርስዎ ገዢ ነዎት",
      youAreSeller: "እርስዎ ሻጭ ነዎት",
      buyer: "ገዢ",
      seller: "ሻጭ",
      quantity: "ብዛት",
      price: "የአንድ መለኪያ ዋጋ",
      total: "ጠቅላላ",
      transactionStatus: "የግብይት ሁኔታ",
      paymentStatus: "የክፍያ ሁኔታ",
      date: "ቀን",
    },
  },

  om: {
    createListing: {
      title: "Oomisha Maxxansi",
      loginRequired: "Oomisha maxxansuuf dura seeni.",
      successTitle: "Oomishni kee maxxanfameera",
      successText: "Oomishni kee amma bitattootaaf ni mul’ata.",
      createAnother: "Oomisha biraa maxxansi",
      viewMyListings: "Oomisha koo ilaali",
    },
    myListings: {
      title: "Oomisha Koo",
      loading: "Fe’aa jira…",
      empty: "Hanga ammaatti oomisha hin maxxansine.",
      errorText: "Oomisha kee fe’uun hin danda’amne.",
      retry: "Irra deebi’i",
      tabAll: "Hunda",
      tabAvailable: "Kan jiran",
      tabSold: "Kan gurgurame",
      noneInFilter: "Gita kana keessatti oomishni hin jiru.",
      addNew: "Oomisha haaraa maxxansi",
    },
    transactions: {
      title: "Daldala Koo",
      loading: "Fe’aa jira…",
      empty: "Hanga ammaatti daldalli hin jiru.",
      errorText: "Daldala fe’uun hin danda’amne.",
      retry: "Irra deebi’i",
      youAreBuyer: "Ati bitaa dha",
      youAreSeller: "Ati gurgurtaa dha",
      buyer: "Bitaa",
      seller: "Gurgurtaa",
      quantity: "Hanga",
      price: "Gatii safartuu tokkoo",
      total: "Waliigala",
      transactionStatus: "Haala daldalaa",
      paymentStatus: "Haala kaffaltii",
      date: "Guyyaa",
    },
  },

  en: {
    createListing: {
      title: "List your produce",
      loginRequired: "Please log in to list produce.",
      successTitle: "Your produce is listed",
      successText: "Your produce is now visible to buyers.",
      createAnother: "List another crop",
      viewMyListings: "View my listings",
    },
    myListings: {
      title: "My listings",
      loading: "Loading…",
      empty: "You have not listed any produce yet.",
      errorText: "Could not load your listings.",
      retry: "Try again",
      tabAll: "All",
      tabAvailable: "Available",
      tabSold: "Sold",
      noneInFilter: "No listings in this group.",
      addNew: "List new produce",
    },
    transactions: {
      title: "My transactions",
      loading: "Loading…",
      empty: "You have no transactions yet.",
      errorText: "Could not load your transactions.",
      retry: "Try again",
      youAreBuyer: "You are the buyer",
      youAreSeller: "You are the seller",
      buyer: "Buyer",
      seller: "Seller",
      quantity: "Quantity",
      price: "Price per unit",
      total: "Total",
      transactionStatus: "Transaction status",
      paymentStatus: "Payment status",
      date: "Date",
    },
  },
};

// Unknown language codes fall back to English instead of crashing.
export const getPageLabels = (lang) => PAGE_LABELS[lang] ?? PAGE_LABELS.en;
